apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "brevesvaultservice.name" . }}-cm"
  labels:
{{ include "brevesvaultservice.labels" . | indent 4 }}
data:
  EXPOSE_PORT: {{ .Values.port | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  DB_HOSTNAME: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
