apiVersion: v1
kind: Service
metadata:
  name: "{{ include "brevesvaultservice.name" . }}"
  labels:
{{ include "brevesvaultservice.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.service.port }}
  selector:
{{ include "brevesvaultservice.matchLabels" . | indent 4 }}
